Add eslint-plugin-mocha
labforward/labforward-config-base pull request #3
Opened 2020-06-05 19:52 UTC by kgrhartlage

I need a rule to stop me from committing `.only` 🙈 

@ignatiusreza recommended [eslint-plugin-mocha](https://github.com/lo1tuma/eslint-plugin-mocha), which has a couple other [rules](https://github.com/lo1tuma/eslint-plugin-mocha/tree/master/docs/rules) that we may or may not like.

Please discuss.

2020-06-06 16:45 UTC, ignatiusreza requested changes

2020-06-06 16:45 UTC, ignatiusreza commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
Let's lock this at `^6.3.0` for now, since eslint 7 drop support for node `< 10.13`.. and latest release of atom still uses node `10.11.0`..

2020-06-08 07:07 UTC, ignatiusreza commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
somewhat related: https://github.com/atom/atom/pull/20764

2020-06-08 07:16 UTC, doktordirk commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
let's use vscode :smile: 

given that list https://eslint.org/blog/2020/02/whats-coming-in-eslint-7.0.0, updating to eslint 7 doesn't seem urgent. so seem no harm to stick to 6 for now

2020-06-08 07:16 UTC, doktordirk commented
not tested but sounds good to me

2020-06-08 10:09 UTC, ignatiusreza commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
> https://atom.io/packages/advanced-open-file

:point_up: The only thing stopping me from fully migrating into vscode..

found [something similar](https://marketplace.visualstudio.com/items?itemName=nocksock.vscode-quick-open-create) but it has a small but annoying differences in behavior.. :sob:

2020-06-09 11:18 UTC, kgrhartlage commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
I assume you came across this one, but in case not, I use [File Utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils)

2020-06-09 11:29 UTC, ignatiusreza commented on package.json
> +    "eslint-plugin-mocha": "^7.0.1",
thanks! I'll give it a try..

2020-06-09 11:30 UTC, ignatiusreza requested changes

2020-06-09 11:30 UTC, ignatiusreza commented on package.json
> +    "eslint-plugin-mocha": "^6.3.0",
you should run `yarn add eslint-plugin-mocha@^6.3.0` instead of editing `package.json` manually.. :grin:

2020-06-09 11:41 UTC, ignatiusreza approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/3970)

2020-06-10 07:32 UTC, doktordirk approved these changes
we'll might need to disable one or two rules on our side initially, but i'm all for it

2020-06-10 07:43 UTC, merged